In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df=pd.read_csv("homeprices1.csv")

In [3]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

# In the bedrooms column there is NaN so we have to manage it.We will fill that with Median of bedroom columns.

In [17]:
import math
bedroom=math.floor(df['bedrooms'].median())
print(bedroom)

4.0


In [19]:
df.bedrooms.fillna(bedroom)
df.bedrooms=df.bedrooms.fillna(bedroom)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [21]:
reg=linear_model.LinearRegression()

In [22]:
reg.fit(df[['area','bedrooms','age']],df['price'])

LinearRegression()

In [23]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [24]:
reg.intercept_

221323.00186540408

# Now predict the Price of (1)-3000 sq ft area,3 bedrooms,40 years old.  (2)-2500 sq ft area,4 bedrooms,5 years old


In [25]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [26]:
reg.predict([[2500,4,5]])

array([578876.03748933])