In [6]:
from word2number import w2n
import pandas as pd
import numpy as np
from sklearn import linear_model

In [22]:
df=pd.read_csv("hiring.csv")

In [23]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [24]:
df.experience=df.experience.fillna("zero")

In [25]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [27]:
df.experience = df.experience.apply(w2n.word_to_num)

In [28]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [30]:
me=df['test_score(out of 10)'].mean()

In [31]:
me

7.857142857142857

In [32]:
import math
mea=math.floor(me)

In [33]:
mea

7

In [34]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(mea)

In [35]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [36]:
reg=linear_model.LinearRegression()

In [37]:
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [38]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [39]:
reg.intercept_

14992.65144669314

# Predict the salary for the employee whose experience is 2 years and test_score(out of 10) is 9 and interview_score(out of 10) is 6

In [40]:
reg.predict([[2,9,6]])

array([53713.86677124])

# Predict the salary for the employee whose experience is 12 years and test_score(out of 10) is 10 and interview_score(out of 10) is 10¶

In [42]:
reg.predict([[12,10,10]])

array([93747.79628651])